"""Generate the offline Mandarin lookup from the pinned Unicode 17.0 Unihan archive."""

from pathlib import Path
import argparse
import hashlib
import json
from zipfile import ZipFile

ROOT = Path(__file__).resolve().parents[1]
SHA256 = "f7a48b2b545acfaa77b2d607ae28747404ce02baefee16396c5d2d7a8ef34b5e"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("archive", type=Path)
    args = parser.parse_args()
    if hashlib.sha256(args.archive.read_bytes()).hexdigest() != SHA256:
        raise ValueError("Expected the pinned Unicode 17.0.0 Unihan.zip archive")
    with ZipFile(args.archive) as archive:
        text = archive.read("Unihan_Readings.txt").decode("utf-8")
    readings = {}
    for line in text.splitlines():
        if "\tkMandarin\t" in line:
            code, _, value = line.split("\t")
            readings[int(code[2:], 16)] = value.split()[0]
    syllables = sorted(set(readings.values()))
    identifiers = {value: index for index, value in enumerate(syllables)}
    output = ["// Generated by scripts/make_pinyin_data.py; see ORIGIN.md and LICENSE.txt.",
              "#pragma once", "#include <cstdint>", "namespace mirrorfly_unihan", "{",
              "    struct Reading { std::uint32_t code; std::uint16_t index; };",
              "    inline constexpr const char* syllables[] =", "    {"]
    output.extend("        " + json.dumps(value, ensure_ascii=False) + "," for value in syllables)
    output += ["    };", "    inline constexpr Reading readings[] =", "    {"]
    output.extend(f"        {{0x{code:X}, {identifiers[value]}}}," for code, value in sorted(readings.items()))
    output += ["    };", "}", ""]
    (ROOT / "third_party/unihan/mandarin_data.hpp").write_text("\n".join(output), encoding="utf-8")
    print(f"Generated {len(readings)} code points and {len(syllables)} readings.")


if __name__ == "__main__":
    main()
